server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /alquileres {
        try_files $uri $uri/ /alquileres/index.html;
    }

    location /clientes {
        try_files $uri $uri/ /clientes/index.html;
    }

    location /vehiculos {
        try_files $uri $uri/ /vehiculos/index.html;
    }
}
