apiVersion: v1
kind: Service
metadata:
  name: hct-cliente-ramirez-fabrizio-service
  namespace: hct-cliente-ramirez-fabrizio
spec:
  selector:
    app: hct-cliente-ramirez-fabrizio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
