apiVersion: v1
kind: Service
metadata:
  name: hct-frontend-ramirez-fabrizio-service
  namespace: hct-frontend-ramirez-fabrizio
spec:
  selector:
    app: hct-frontend-ramirez-fabrizio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer