apiVersion: apps/v1
kind: Deployment
metadata:
  name: hct-vehiculo-ramirez-fabrizio-deployment
  namespace: hct-vehiculo-ramirez-fabrizio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hct-vehiculo-ramirez-fabrizio
  template:
    metadata:
      labels:
        app: hct-vehiculo-ramirez-fabrizio
    spec:
      containers:
      - name: hct-vehiculo-ramirez-fabrizio-container
        image: fabrizioleonardoramirez/hct-vehiculo:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: hct-vehiculo-ramirez-fabrizio-secret
